"""empty message

Revision ID: 07f77c4b622c
Revises: d160ae2e5e29
Create Date: 2016-07-15 21:43:20.653112

"""

# revision identifiers, used by Alembic.
revision = '07f77c4b622c'
down_revision = 'd160ae2e5e29'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flask_dance_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('token', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('presentation_user_id_fkey', 'presentation', type_='foreignkey')
    op.drop_table('flask_dance_user')
    op.create_foreign_key(None, 'presentation', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'presentation', type_='foreignkey')
    op.create_foreign_key('presentation_user_id_fkey', 'presentation', 'flask_dance_user', ['user_id'], ['id'])
    op.create_table('flask_dance_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('token', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('github_name', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='flask_dance_user_pkey'),
    sa.UniqueConstraint('email', name='flask_dance_user_email_key')
    )
    op.drop_table('flask_dance_oauth')
    op.drop_table('user')
    ### end Alembic commands ###
