"""empty message

Revision ID: 6942f5ec2ca7
Revises: 07f77c4b622c
Create Date: 2016-07-19 12:01:34.582445

"""

# revision identifiers, used by Alembic.
revision = '6942f5ec2ca7'
down_revision = '07f77c4b622c'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('meetup_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['meetup_id'])
    op.drop_constraint('flask_dance_oauth_user_id_fkey', 'flask_dance_oauth', type_='foreignkey')
    op.create_foreign_key(None, 'flask_dance_oauth', 'user', ['user_id'], ['meetup_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'meetup_id')
    op.drop_constraint(None, 'flask_dance_oauth', type_='foreignkey')
    op.create_foreign_key('flask_dance_oauth_user_id_fkey', 'flask_dance_oauth', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###
